### ISSUE TITLE
Doesn't work with  Laravel 6 and above

### ISSUE THREAD

**Issue by rtuble** [bluora/laravel-model-json#23]
Does anyone able to use this for Laravel 6 and above? I tried to upgrade and it failed because of this package had to remove it for my upgrade to work.

**Comment by RoccoHoward** [comment]
Hey @rtuble. Sorry for delay.

I haven't used it for awhile now- it really solved things back in the day, but with casting in L7-8, I've not come back to a need for this which is why I haven't spent any time bringing it up to the latest version.

If someone can PR any changes that would be needed, happy to review and merge.

**Comment by rtuble** [comment]
> 
> 
> Hey @rtuble. Sorry for delay.
> 
> I haven't used it for awhile now- it really solved things back in the day, but with casting in L7-8, I've not come back to a need for this which is why I haven't spent any time bringing it up to the latest version.
> 
> If someone can PR any changes that would be needed, happy to review and merge.

No worries, I just bypassed this package and just updated the codes using it to use native json manipulation.
